[Settings]
ID = "b41224e5-2148-49c0-b2be-7400424b6f26"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  
[build]
  # This is the directory to change to before starting a build.
  base    = "news_app"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "news_app/build/"
  # This will be your default build command
  command = "yarn build"

      from = "/*"

    to = "/index.html"

    status = 200
